name: thesis_kevin
channels:
  - default
  - rdkit
dependencies:
  - cherrypy=18.1.0
  - numpy=1.16.2
  - pandas=0.24.2
  - matplotlib=3.0.3
  - pip=19.0.3
  - python=3.6.7
  - scipy=>1.0.0
  - setuptools=40.8.0
  - scikit-learn=0.20.3
  - statsmodels=0.9.0
  - rdkit=2018.09.2.0
  - pyyaml=5.1
  - requests=2.21.0
  - pytest=4.3.1
  - psycopg2=2.8
  - pip:
     - django
     - djangorestframework
     - django-cors-headers
     - djangorestframework-yaml
     - "https://github.com/phi-grib/standardiser/archive/master.zip"
     - "https://github.com/josecarlosgomezt/nonconformist/archive/master.zip"
